### ISSUE TITLE
Create a HTML page to show ThingSpeak graphs

### ISSUE THREAD

**Issue by WillianRod** [utfpr/HortaOS#1]
Create a directory `page` where you will put all the needed files to the creation of a static page to show graphs from  [ThingSpeak](https://thingspeak.com/channels/370192/)

**Comment by WillianRod** [comment]
@andreyazevedo The name `HortaOS` and put the name of the university somewhere `Universidade Tecnológica Federal do Paraná` and the graphs. Nothing more, for now

**Comment by WillianRod** [comment]
@andreyazevedo If possible, make it pleasent to the eyes

**Comment by andreyazevedo** [comment]
All right. I will work on this :)

**Comment by andreyazevedo** [comment]
All right. I will work on it :)

**Comment by andreyazevedo** [comment]
done 

https://github.com/utfpr/HortaOS/pull/4

**Comment by WillianRod** [comment]
Thanks @andreyazevedo for your help. Your contribution is now live on https://utfpr.github.io/hortaos/
